[tool.poetry]
name = "fastapi-auth0-backend"
version = "0.1.0"
description = "A FastAPI server for authentication (login) and autherization (scopes) using auth0 service"
authors = ["roy-pstr <roy.pasternakk@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.2"
fastapi = {extras = ["all"], version = "^0.87.0"}
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
auth0-python = "^3.24.0"
pydantic = "^1.10"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
pylint = "^2.15.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
